# Generated by Django 4.0.4 on 2022-05-07 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['sending_datetime']},
        ),
        migrations.AlterField(
            model_name='content',
            name='content_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base.contenttype'),
        ),
        migrations.AlterField(
            model_name='content',
            name='sending_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='subject',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
